### ISSUE TITLE
Improve performance of `query` functions

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1009]
# Problem

I did a performance audit and saw that we call the get function several times. The function is looping over all messages.

<img width="716" alt="image" src="https://github.com/inlang/inlang/assets/58360188/fa1cb7d5-55cf-4c9a-a9f2-2924bd6611cc">

This slows down the push event tremendously.

@inlang/editor 
@inlang/lisa

**Comment by araknast** [comment]
Hmm, I was suspicious something like this was happening, possibly related to https://github.com/inlang/inlang/issues/345

Will investigate further.

**Comment by samuelstroschein** [comment]
Query can be heavily performance optimized. 

I implemented query in a simple and naive way (on purpose). I tried to made the API future-proof with `query().x` so that the query() function can conduct performance optimizations like retrieving messages from a Map (O(1)) instead of iterating over every message (O(n)) for example.

1. IMO the performance issues of query should be solved within query. The editor should be able to call `query().get` however often it is desired without worrying about performance. 

2. If `query()` uses module scoped state, the performance optimizations should "automatically" spill over to `lint` and other modules that use `query` internally. If module scoped state is the way to go, query would need to cache data for resources which should be doable because resources use ids. 

But, how to detect changes from a resource aka cache invalidation?

**Comment by araknast** [comment]
> @samuelstroschein I implemented query in a simple and naive way (on purpose). I tried to made the API future-proof with query().x so that the query() function can conduct performance optimizations like retrieving messages from a Map (O(1)) instead of iterating over every message (O(n)) for example.

Implementing `Map` seems like a quick way to drastically improve performance then, does someone want to take this over? 

Also noted heavy use of `JSON.parse(JSON.stringify())`. Could we:
1. Replace `JSON.parse(JSON.stringify())` with `structuredClone` or
2. Use `Object.freeze` to render objects immutable, circumventing the need to copy them?

> IMO the performance issues of query should be solved within query. The editor should be able to call query().get however often it is desired without worrying about performance.

Agreed.

> If query() uses module scoped state, the performance optimizations should "automatically" spill over to lint and other modules that use query internally. If module scoped state is the way to go, query would need to cache data for resources which should be doable because resources use ids.

Not sure what is meant by "module scoped state" here. What does  "state" for each module look like currently?

**Comment by samuelstroschein** [comment]
> @araknast  Not sure what is meant by "module scoped state" here. What does "state" for each module look like currently?

That query caches functions "in the scope of the query module". 

```ts

// module scoped state (not exported)
const cache = {}

export get() {
  return cache
}
```

**Comment by araknast** [comment]
>  Seems like a longer task. Cache invalidation will be difficult (as always). Given that you are deep down profiling the editor, you should be best suited to implement caching?

I would need to wait until after completing `objectStoreFs` to work on it. If no one else is available though I can take it on.

> That query caches functions "in the scope of the query module".

Ok I think I see. If we have two lisa repositories, one synced to the filesystem and one only in memory, we could use the in-memory repo as a "cache". Then we sync on write, and on read we simply compare the hashes to see if we need to sync again. 

Of course, this would require some sort of filesystem monitoring to keep the "filesystem" repo in sync with the actual filesystem.

**Comment by samuelstroschein** [comment]
> @araknast  If we have two lisa repositories, one synced to the filesystem and one only in memory, we could use the in-memory repo as a "cache". Then we sync on write, and on read we simply compare the top level tree hashes to see if we need to sync again.

Let the requirement to sync the cache between apps arise first ;) 

I thought a bit about cache invalidation. 

CRUD operations via `query` are simple because we have full control. For example, we could mutate a given resource and attach a `_query` property that signals that a resource is cached. If a resource is modified externally, the `_query` property will be missing, signaling that the (entire) cache should be invalided. Ofc, this is an incremental performance optimization. However, the performance gains could be enough, and a second optimization looks into caching with external modifications.

**Comment by NilsJacobsen** [comment]
So should we close this and put it in the 'support big repos' project?

**Comment by araknast** [comment]
@NilsJacobsen Probably close this for now until `remoteObjectStoreFs` is finished. Unless someone else wants to take it on.

**Comment by samuelstroschein** [comment]
I could take it on. But, I should get out of coding tasks. 

Let's do the following. I assign the task to myself. If I have time, I'll implement a quick win that improves inlang's performance across every app. Otherwise, I'll close the issue.

**Comment by samuelstroschein** [comment]
Closing as "low priority". 

I will not be able to work on this issue this week.

**Comment by samuelstroschein** [comment]
Duplicate discussion in https://github.com/inlang/inlang/discussions/1075
