### ISSUE TITLE
expose `messageId` in `LintReport`

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#1072]
## Context

We currently do not expose the `messageId` (for example `this.example` or `this:example`) in the lint report.
We only expose the `id` of the `LintRule`, for example `inlang.missingReference`, which also makes sense, but isn't of the biggest importance to the user.

https://github.com/inlang/inlang/blob/ad6f2b3b1ab369a19002918b75f3ff8ae7921d6a/source-code/core/src/lint/rule.ts#L25-L32

This leads to "buggy" implementations, where the `messageId` has to be searched in the `message` string.

https://github.com/inlang/inlang/blob/09a90ae3d8c6f41906801ce04c0cf05dc3ad65b3/source-code/ide-extension/src/diagnostics/linterDiagnostics.ts#L40-L42

There are other examples, for example with the badge, too.

## Proposal
Expose `messageId` alongside `id` in `core/lint`.

@inlang/core 

@inlang/ide-extension This could be interesting for you too, because the example has been made with the ide extension.

**Comment by samuelstroschein** [comment]
@ivanhofer the request seems to make sense, doesn't it?

**Comment by NiklasBuchfink** [comment]
Is this issue related to this discussion?
https://github.com/inlang/inlang/discussions/574#discussioncomment-5717270

In this case, the @inlang/editor would also benefit from it. We came up with a complex logic for filtering by lint rule, see:
https://github.com/inlang/inlang/blob/main/source-code/website/src/pages/editor/%40host/%40owner/%40repository/helper/handleMissingMessage.ts 

I have yet to look into it, but this could also be the root cause of badge issue #974.

**Comment by felixhaeberle** [comment]
I smell something important here 😄

**Comment by samuelstroschein** [comment]
> @NiklasBuchfink  Is this issue related to this discussion https://github.com/inlang/inlang/discussions/574#discussioncomment-5717270

Likely. 

There seems to be a design flaw in the linting system. Namely, attaching lints to the AST. 

- some lints are unrelated to the AST, leading to edge cases like https://github.com/inlang/inlang/discussions/574#discussioncomment-5717270 and #974 
- separation of concerns is violated. the AST is a representation of messages in resources. lints use the AST, but are something else. 

## Proposal 

Unbundle the linting system from the AST. 

- no more AST edge cases
- separation of concerns
- the AST types become vastly simpler because the concept of "extending the AST" is redundant (https://github.com/inlang/inlang/blob/09a90ae3d8c6f41906801ce04c0cf05dc3ad65b3/source-code/core/src/ast/schema.ts#L28)

Vote with 👍 or 👎

**Comment by NilsJacobsen** [comment]
@felixhaeberle how would your desired lintReportType look like?

**Comment by felixhaeberle** [comment]
@NilsJacobsen I don't know what you are referring to.

**Comment by ivanhofer** [comment]
The id of the message is not included in the payload because it is is redundant information. A lint report is attached to a node, so the information can be retrieved from there when qerying.
It probably makes sense to go for #1074 if the current implementation causes problems.

**Comment by felixhaeberle** [comment]
@ivanhofer For convenience reasons, there is `getLintReport` which doesn't give me the message id as property. 

The unbundling in every app causes, as Niklas mentions, bugs and overhead so I strongly advise for adding the messageId at least as output of the `getLintReport` function.

**Comment by samuelstroschein** [comment]
@felixhaeberle MessageID will be returned when #1074 is implemented.

**Comment by felixhaeberle** [comment]
@samuelstroschein Why are you jumping into coding tasks? 😄 Because of core?

**Comment by samuelstroschein** [comment]
@felixhaeberle I will scope the issue. Didn't plan on coding the issue. Although, I could that if nobody else can. TBD

**Comment by samuelstroschein** [comment]
Follow up proposal in #1099
