### ISSUE TITLE
invalid inlang config because languages don't match up. 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1082]
## Problem

From @jonator 

I'm getting this on stage branch of osmosis
We don't have a list of languages in the config file

```
~/Dev/osmosis-frontend (jonator/cl/translate) » yarn machine-translate                                                                                       jonator@jonsmac
yarn run v1.22.19
$ inlang machine translate

 ERROR  Error: The inlang.config.js is invalid.                                                                                                                    22:10:46

# The following errors occurred during the setup of plugins:

None ✅

# The following errors occurred during the validation of the config:

The list of languages in the config file does not match the returned resources from `readResources()`.

---

If plugins return errors, chances are high that the plugin errors are the root cause
for the config errors. Try to fix the plugin errors first.

    at setupConfig (file:///Users/jonator/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:68539:11)
    at async getConfig (file:///Users/jonator/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:68657:19)
    at async file:///Users/jonator/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:69441:22

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior

Don't fail.

## Steps to reproduce

1. Open https://github.com/osmosis-labs/osmosis-frontend/blob/stage
2. Go to the staging branch
3. Run machine translate

**Comment by samuelstroschein** [comment]
@inlang/plugins can you investigate?

**Comment by NilsJacobsen** [comment]
Hey @jonator, I looked into your problem and released a patch to the json plugin. 

The problem was the `__tests__` folder added last week. It was detected as a language by the getLanguage detection. I adjusted the ignore property to also work with folders. 

So you need to add the `ignore: ["__tests__"]`to your plugin settings. I already did that for you in this PR -> https://github.com/osmosis-labs/osmosis-frontend/pull/1827

**Comment by jonator** [comment]
Will LYK if it fixes it

**Comment by MaxMillington** [comment]
Just reran it with the `ignore: ["__tests__"]` option. Still getting:

```
 ERROR  Error: The inlang.config.js is invalid.                                                                                                                                                                                            16:15:27

# The following errors occurred during the setup of plugins:

None ✅

# The following errors occurred during the validation of the config:

The list of languages in the config file does not match the returned resources from `readResources()`.

---

If plugins return errors, chances are high that the plugin errors are the root cause
for the config errors. Try to fix the plugin errors first.

    at setupConfig (file:///Users/michaelmillington/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:68539:11)
    at async getConfig (file:///Users/michaelmillington/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:68657:19)
    at async file:///Users/michaelmillington/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:69441:22
    ```

**Comment by jonator** [comment]
``` ERROR  Error: The inlang.config.js is invalid.                                                                                                                                                                                            16:15:27

# The following errors occurred during the setup of plugins:

None ✅

# The following errors occurred during the validation of the config:

The list of languages in the config file does not match the returned resources from `readResources()`.

---

If plugins return errors, chances are high that the plugin errors are the root cause
for the config errors. Try to fix the plugin errors first.

    at setupConfig (file:///Users/michaelmillington/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:68539:11)
    at async getConfig (file:///Users/michaelmillington/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:68657:19)
    at async file:///Users/michaelmillington/Dev/osmosis-frontend/node_modules/@inlang/cli/dist/main.js:69441:22
    ```
    
Seems to remain an issue
@NilsJacobsen

**Comment by NilsJacobsen** [comment]
The patch should have fixed it. But the link: https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js is not pointing to the latest 3.0.9 patch. 

Error still there:
(stage branch) https://inlang.com/editor/github.com/osmosis-labs/osmosis-frontend

When pointing directly to the patch, you get no error: (see my fork) https://inlang.com/editor/github.com/NilsJacobsen/osmosis-frontend

For a quick fix, you can point to https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3.0.9/dist/index.js, but that does mean that you do not get further patches and minor changes. Maybe it is a cache problem? I assume it will be referred automatically to 3.0.9 in a few hours. 

As I said, I would point to the new version if it needs to be fixed now. Otherwise, checking the cache or just waiting should resolve it.

**Comment by samuelstroschein** [comment]
@NilsJacobsen you have to purge jsdelivr's cache https://www.jsdelivr.com/tools/purge

@MaxMillington @jonator should work now. I purged the cache!

**Comment by NilsJacobsen** [comment]
Okey @jonator I purged jsdelivr cache manually. It works again: https://inlang.com/editor/github.com/osmosis-labs/osmosis-frontend

If the editor is still broken u need to clear the cache in the browser.

**Comment by NilsJacobsen** [comment]
Can you confirm? :)

**Comment by MaxMillington** [comment]
Thanks!
