### ISSUE TITLE
Improvement of dogfooding

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#1119]
- [x] QA for German translations
- [x] Accessible and nice-looking language picker
- [x] Chinese translation
- [x] localize header & footer

**Comment by NilsJacobsen** [comment]
@inlang/editor

**Comment by ivanhofer** [comment]
- [ ] hide language picker where we don't have translations
- [ ] no flags in language picker
- [ ] less prominent language picker
- [ ] replace "us" with "en"
- [ ] "German" should be "Deutsch"
- [ ] switching language sometimes alters the url to this
   ![image](https://github.com/inlang/inlang/assets/21335119/61ba17cf-de74-4a75-b8e9-5021cdaa0833)
- [ ] once I switch language on `/de` i stay on `/de` and don't get redirected to `/en`

**Comment by NilsJacobsen** [comment]
> switching language sometimes alters the url to this

What did you do to get to this URL?

**Comment by felixhaeberle** [comment]
@NilsJacobsen
- go to /documenation
- switch german
- reload 
- switch english
- switch german

additonally, the lang switcher doesn't make sense on the docs rn because the docs aren't localized yet

<img width="1277" alt="Bildschirmfoto 2023-07-18 um 14 53 36" src="https://github.com/inlang/inlang/assets/34959078/fec3af1f-d202-4fd0-9e73-5547765550c6">
