### ISSUE TITLE
design flaws that should be addressed in core

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#1144]
## Context

@inlang/team Participate in the referenced issues. I plan on doing a call tmr (20 July) to discuss things (if required). 

LOOM https://www.loom.com/share/4611de77b168423694fe53771ae6a49f 📹 

- during https://github.com/orgs/inlang/projects/35 more (highly likely) design flaws became apparent
- addressing those design flaws now is a unique opportunity because we can still manually update every config with PRs 

## Design flaws 

- [ ] https://github.com/inlang/inlang/issues/1143
- [ ] https://github.com/inlang/inlang/issues/1140

## question

Should we resolve the design flaws now at the risk of a big breaking change?

**Comment by NilsJacobsen** [comment]
That's right, with the creation of the inlang instance, we can hide all that complex config stuff and work with an easy json. I also support that apps can change user settings.

My feeling: Prosal is better 👍 

My biggest concern is that this will result in a big braking change. 👎 
How can we make the transition smooth? Can we support both configs for some time? If we need maintainer input to make that work, I'm not sure if it's worth it losing superspreaders. (The best product will not help us in the next round, it's the users)

**Comment by samuelstroschein** [comment]
> How can we make the transition smooth? Can we support both configs for some time? If we need maintainer input to make that work, I'm not sure if it's worth it losing superspreaders. (The best product will not help us in the next round, it's the users) 

The change is so big that I don't know if the effort is worth it. But: 

- the only requirement is that apps transform the config from JS to JSON. 
- for large repos, we can hardcode the config that an app should create based on their existing app :D
- for other repos, we can try to "auto migrate". not sure if it worth though

**Comment by felixhaeberle** [comment]
We could write an codemod which transforms the js to a json, so this part would be "automated". 

We can even read the languages from the resource folder and add them to the json, because we know the resource path (and what should potentially be excluded).

But the codemod has to be executed manually. In each project. An appealing solution could be to introduce an temporary cli command `config codemod` which can be used by the maintainer and we tell this the maintainer via a setup error message in the new system.

**Comment by samuelstroschein** [comment]
Let's create a dedicated issue on how we can migrate the config. @felixhaeberle could you do that? 

For this discussions, a very interesting question is: Do more design flaws exist that should be addressed?

**Comment by NilsJacobsen** [comment]
I'm unsure about having the languages in the config.json file. Cause the source of truth are the resource files and not a list in the config. Plus, it makes the config unnecessarily long. You can also already add it from apps by adding the specific files to resources.

**Comment by samuelstroschein** [comment]
> I'm unsure about having the languages in the config.json file. Cause the source of truth are the resource files and not a list in the config.  

Resources being a source of truth is a design flaw that leads to limited apps that can't even add a language. 

I feel strongly about forcing languageTags to be defined in the config. For legacy purposes, we can let plugins `extendLanguageTags`. Hence, a user could have `languageTags: []` as a legacy workaround. However, resources are not the source of truth. They are just storage.

**Comment by NilsJacobsen** [comment]
But that is confusing, why should I add a language twice? 
What is the reason to not see the resources as source of truth?
What are the benefits of having the tags in the config?

**Comment by felixhaeberle** [comment]
> I'm unsure about having the languages in the config.json file. Cause the source of truth are the resource files and not a list in the config. Plus, it makes the config unnecessarily long. You can also already add it from apps by adding the specific files to resources.

In no business circumstance you want the existence of a file to decide which language to support. This should be carefully considered at the manager level and should then be explicitly declared. Otherwise, managers and translators will hate you. 
Furthermore, it makes adding languages better and can be picked up (for example) by machine translate.

> To overcome the the long lists of languages we could introduce short handles for "groups", like "eu", "world/all" – but that's an highly experimental thought.

**Comment by NilsJacobsen** [comment]
In my eyes it just adds duplication and missmatch

**Comment by samuelstroschein** [comment]
> What are the benefits of having the tags in the config? 

Every app knows exactly what languageTags are supposed to be supported by a project. 

An app aka user can now modify the languageTags config to add languages to a project without being dependent on a resource or developer. @NilsJacobsen users can't add a language tag in the editor. That is just nuts! The reason is the flaw that resources are the source of truth. They are not. They are just mere storage. If a project adds a new language tag, it is logical that a resource for it doesn't exist yet. Forcing the creation of resources before a language tag can be added is just wrong. 

> @NilsJacobsen  In my eyes it just adds duplication and mismatch

For legacy projects. New projects use the inlang config as source of truth, see the SDK. 

> @felixhaeberle To overcome the the long lists of languages we could introduce short handles for "groups", like "eu", "world/all" – but that's an highly experimental thought.

No please not. Just stick to BCP47 language tags.

**Comment by felixhaeberle** [comment]
> In my eyes it just adds duplication and missmatch

Messages could soon come from a database file or something completely different. 
Why rely on multiple files explicit names so strong?

**Comment by NilsJacobsen** [comment]
🤔 I'm still not convinced to hardcode languageTags in the config

Pro:
- non-tech people can use CRUD on config to add languages -> This results in non-empty language folders/files (may reduce bugs)

Cons:
- Feels like duplication (the files need to be named after the language tag anyway, and it also needs to be defined in the config)
- When we have legacy extendLanguageTags + additional languageTags from the config, that would confuse devs.
- There are devs that are not using inlang. Not forcing them to use inlang is one of inlang's benefits. They would add the resources but do not want to touch the config.
- addLanguage can be handled by plugins (they currently do, i18next with good test bugfree, in the future with end2end)
- config get's longer (feels less smart)

**Comment by samuelstroschein** [comment]
> addLanguage can be handled by plugins (they currently do, i18next with good test bugfree, in the future with end2end)

You are proposing to push a problem (adding a language) onto the ecosystem. Every resource plugin needs to provide this hook, and it needs to work every time. Disaster waiting to happen is the consequence:

> "Why can't I add a language tag"? "The plugin doesn't support it"

> "Why does adding a language tag lead to crashes?" "Ergh, sorry we can't help. Please contact the maintainer to make a bugfix and update your plugin".

**Comment by felixhaeberle** [comment]
> Feels like duplication (the files need to be named after the language tag anyway, and it also needs to be defined in the config)

for me, the duplication here is no duplication but a config-based, crud-compatible "control layer" of languages, where the files are only the resources we load from.

> When we have legacy extendLanguageTags + additional languageTags from the config, that would confuse devs.

- `extendLanguageTags` is only what plugins use, this is not exposed to regular devs
- everything emerges around `languageTags`

> There are devs that are not using inlang. Not forcing them to use inlang is one of inlang's benefits. They would add the resources but do not want to touch the config.

Can you further elaborate? I don't understand this point yet.

> addLanguage can be handled by plugins (they currently do, i18next with good test bugfree, in the future with end2end) 

That's why `extendLanguageTags` is still in place, but with the proposal we now have a config-based, crud-compatible "control layer".

> config get's longer (feels less smart)

That shouldn't be a problem? and only very few projects would have more than 10+ languages. Making it less smart lowers the friction of using it -> next.js/image: too "smart", big shitstorm. now complete redesign.

**Comment by NiklasBuchfink** [comment]
I like the proposal and I think a crud-compatible configuration provides opportunities for features that lead to better UX and DX over inlang applications.

In addition, I suggest the following:
- Add an option to generate language tags automatically when creating the `inlang.config.json` for the first time
- Add a lint rule and `lint --fix` if the resources don't align with the config. (better error handling, show a prompt to solve this, request approval with the introduction of roles and review processes in the future)
- Derive best practices for "Building apps on Lisa" from these design flaws

**Comment by felixhaeberle** [comment]
> Add an option to generate language tags automatically when creating the inlang.config.json for the first time

Are you referring to `extendLanguageTags` which is not only executed in runtime but in setup?

**Comment by NiklasBuchfink** [comment]
> @NiklasBuchfink Are you referring to `extendLanguageTags` which is not only executed in runtime but in setup?

@felixhaeberle Yes, I thought we could keep this as an option in the setup to derive the language tags and be up and running quickly. On second thought, it makes the plugins more complex and has been a source of errors in the past. It leads to more edge cases during plugin development. My proposal to have it only in the setup would diminish the return on the time invested to support this feature.

**Comment by NilsJacobsen** [comment]
Summary of call with @samuelstroschein,

when you see the languageTags in the config more like a plan aka 'What languages do we plan to support', your way of thinking makes more sense. Also, if translators/managers/devs use an inlang frontend/interface to add a language that adds it to the config, would work perfectly fine. 

The only problem I see is when devs manually add files (or other types of resources), because that is the way you do it today in a lot of apps. In that case, we have a mismatch. That's where the extendLanguageTags can help. 

How can we prevent misunderstanding from devs?
- Have good docs
- Maybe deliver a docs template for their docs. Most of os projects have an i18n section where they describe the process. When that is clear, we do not have a problem here, and we can push for languageTags in config.

Just an experimental thought to prevent others from thinking like me:
What if we name it allowedLanguageTags to make it more clear? With an inlang interface, you can extend that list (editor add language), but it is clear, that just because they are in the array, there doesn't need to be a resource for that. If the allowedLanguageTags is empty, it implies that extendLanguageTags is deriving the tags.

**Comment by ivanhofer** [comment]
shared my thoughts on the issue: https://github.com/inlang/inlang/issues/1143#issuecomment-1643847060

**Comment by samuelstroschein** [comment]
Closing as "both issues will be addressed in #1142"
