### ISSUE TITLE
How should the UI for the user look if there are more ways to interact with each marketplace item?

### ISSUE THREAD

**Issue by floriandwt** [inlang/inlang#1265]
## Context
The marketplace should be able to allow installing modules directly from it, otherwise its a bad experience for the user and nothing has changed to the plugin registry. Therefore, a different design has to be discussed for how the user interacts with single items.

FYI, the marketplace interaction right now is the same as in the docs (redirect to GitHub).

Example meta data right now that gets rendered:
```js
meta: {
		id: "inlang.plugin.json",
		displayName: { en: "Plugin JSON" },
		description: { en: "JSON plugin for inlang" },
		marketplace: {
			icon: "https://github.com/inlang/inlang/blob/main/source-code/plugins/json/assets/icon.png?raw=true",
			linkToReadme: { en: "https://github.com/inlang/inlang/tree/main/source-code/plugins/json" },
			keywords: ["json", "generic"],
			publisherName: "@inlang",
			publisherIcon: "https://inlang.com/favicon/safari-pinned-tab.svg",
		},
	},
```

## Proposal 1 – The user can install modules when clicking cards
**Pros**
- UI doesn't change much
- Quite easy to change the behavior when clicking on cards

**Cons**
- The user doesn't know what happens when clicking on a card until he does it
- Showing other information the user could be interested in e.g. link to the README is not possible to implement (too little space, too much content anyways)

## Proposal 2 – A popup opens with more information and two buttons (e.g. Install, Readme)

**Pros**
- No redirection to a new page, but more space for further information and UI elements
- We decided against it for now, but #1246 could be implemented to that.

**Cons**
- No SEO advancement (if we render pages for every item, it could have an immense impact on our SEO)
- More clicks for the user

## Proposal 3 – A subpage instead of a popup with more information

**Pros**
- Good for SEO
- Same as above (We decided against it for now, but #1246 could be implemented to that.)

**Cons**
- Redirect to another page could be UX flaw
- Too little info for now

**Comment by floriandwt** [comment]
@inlang/team please discuss the proposals on how to display information without destroying a good UX.

I'm for Proposal 2, we don't confuse the user and at the same time, we can easily take the content from inside the modal and render it as a subpage of the marketplace (e.g. like Raycast does, but for that, our marketplace has to be much bigger).

**Comment by jannesblobel** [comment]
I vote for Proposal 2 

- prop 1 is not intuitive. The user would not expect an install, or you have to add a button on the card
- prop 3 if you want to add more than 1 item, it is annoying to go back and forth on pages 


Is it possible to use `iframes` to have the SEO benefits from proposal no.3 and display the content in a modal?

**Comment by floriandwt** [comment]
@jannesblobel I can't imagine iframes helping SEO. Nowadays there are better options to embed things in such a use-case with SEO advantages too (e.g. https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes -> a combination).

**Comment by NiklasBuchfink** [comment]
I vote for Proposal 2:
- UX-wise the best with an app feel
- suitable for the amount of information we receive and want to show
- SEO should be doable

What would be the flow for the installation? You need to install it into a config of a repo. If a config exists, we can clone the repo as we do in the editor and add everything with the `setConfig`function.

**Comment by samuelstroschein** [comment]
Proposal 1 is not good.
Proposal 2 is meh because nobody likes pop-ups. 
Proposal 3 is the future (can you implement this in 1 week is the question. if the answer is yes, we should likely go for the best solution directly)

### Counter-proposal (if proposal 3 is unsuitable):

Why not use the cards to directly link to the readme and install callback? 

- (the mock is out of proportion. don't judge the button sizes etc.)
- no hover logic, no popup 

<img width="636" alt="CleanShot 2023-08-18 at 15 59 03@2x" src="https://github.com/inlang/inlang/assets/35429197/12a0060d-f810-4a3c-97c3-987aa342db56">

**Comment by jannesblobel** [comment]
@samuelstroschein 
Your Proposal could be a bit overwhelming on the entire page. The user does not know where to look first 
<img width="522" alt="CleanShot 2023-08-18 at 16 25 37@2x" src="https://github.com/inlang/inlang/assets/72493222/285e3720-1cc4-4d39-b815-cfe2884ff393">

**Comment by jannesblobel** [comment]
> Proposal 2 is meh because nobody likes pop-ups.

I believe this is dependence on the purpose

**Comment by jannesblobel** [comment]
Let's take the best practice.

-> click on the card to open a new page 
-> click on install/get install item 

<img width="517" alt="CleanShot 2023-08-18 at 16 36 38@2x" src="https://github.com/inlang/inlang/assets/72493222/f116df42-ce0f-4e63-84cf-16b3e0818afc">

**Comment by floriandwt** [comment]
In which context is "get" necessary? for the apps?
And I think it is not good to have one hover element over another, that's really complicated because the cards then also must have a hover effect.

**Comment by NiklasBuchfink** [comment]
If we agree that we have too much information on one sight, we need to use progressive disclosure and show the most important information first on the card and then show the rest on a separate page after an action by the user.

I would pick a modal for that:
- we don't have that large amount of content to show
- app-like feel (because of a transition) and supports mental modal
- easy to do with a library
- no hover, just open and close or click-outside

**Comment by samuelstroschein** [comment]
1. How about my counter-proposal to keep things simple but with progressive disclosure like @NiklasBuchfink mentioned: 

- on hover, an install and readme button is  rendered BUT NOT A POPUP OR MODAL

<img width="574" alt="CleanShot 2023-08-18 at 17 23 51@2x" src="https://github.com/inlang/inlang/assets/35429197/3ea37a6c-85f2-4d68-a314-4b8d77029a38">

2. @floriandwt If you can implement proposal 3 within one week, we can also go for dedicated pages for the sake of a better UX and SEO. You have to tell us if that's manageable. Rendering the readme should be part of proposal 3 then though


---

> @NiklasBuchfink If we agree that we have too much information on one sight, we need to use progressive disclosure and show the most important information first on the card and then show the rest on a separate page after an action by the user. 

Agree. 

> @NiklasBuchfink I would pick a modal for that

Um gottes willen, bloß kein modal. modal sind für "_disrupts a user workflow_ because immediate action is required". nen module zu installieren soll nicht den workflow disrupten.

@jannesblobel what is 'get' for?

**Comment by jannesblobel** [comment]
Example Stores 

- https://www.raycast.com/store
- https://plugins.jetbrains.com/
- https://www.figma.com/community/category/visual-assets/plugins
- Apple App store
- https://play.google.com/store/games?gl=DE
- https://marketplace.visualstudio.com/
- https://www.notion.so/integrations/all

**Comment by floriandwt** [comment]
Ok thanks, I will take the following steps:
1. build the installation logic (because its the foundation of this whole action)
2. edit the cards to the layout @samuelstroschein proposed without the modal / popup (such a layout / style change is implemented fast)
3. if everything else works: implement the markdown rendering of the readmes and the dynamic creation of each page, I can better calculate how long it takes if the other necessities are done

add point 1 + 2 to should have and 3 to nice to have

**Comment by floriandwt** [comment]
Closing as we came to a conclusion on how we continue (see #1242 scope)

**Comment by samuelstroschein** [comment]
@floriandwt i recommend writing the conclusion as future reference point. 

"Closing as we came to a conclusion on how we continue" -> What's the conclusion?
