### ISSUE TITLE
rethink project folder structure

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#1274]
## Sub-tasks

- [x] #1306

**Comment by samuelstroschein** [comment]
Agree, the folder structure is messy. A few observations: 

- /core is not required anymore. No core exists anymore 🤷‍♂️ Inlang now consists of libraries that are bundled in inlang/app to build inlang apps
- the monorepo will likely expand beyond inlang, starting with lisa. scoping between different products should exist.
- the monorepo will likely contain non-code related stuff like the handbook, documents, assets (already does)  

### Some proposals

Folder structure 1

- the most "scalable" solution by scoping different projects and separating source-code from non code related stuff
- can be easily extended in the future by adding `lisa/carrers/software-engineer.md` or other things 

```
.
├── lisa/
│   ├── source-code/
│   │   ├── client
│   │   ├── server
│   │   └── filesystem
│   ├── documentation
│   └── README.md
├── inlang/
│   ├── source-code/
│   │   ├── apps
│   │   ├── plugins
│   │   ├── lint-rules
│   │   └── libraries
│   ├── documentation
│   └── README.md
├── careers
├── documents
├── website
└── ...
```

Folder structure 2

- use folders as "namespaces". global stuff is in the root like website, careers, documents. scoped stuff in a sub-folder without sourc-ecode because source-code separation is not required at the moment

```
.
├── lisa/
│   ├── client
│   ├── server
│   ├── filesystem
│   ├── documentation
│   └── README.md
├── inlang/
│   ├── apps
│   ├── plugins
│   ├── lint-rules
│   ├── libraries
│   ├── documentation
│   └── README.md
├── careers
├── documents
├── website
└── ...
```

Folder structure 3

- scope code stuff under source code for distinguishing "code stuff" from non-code stuff (documents etc) 
- makes monorepo setup with NPM workspaces etc easier

```
.
├── source-code/
│   ├── lisa/
│   │   ├── client
│   │   ├── server
│   │   ├── filesystem
│   │   ├── documentation
│   │   └── README.md
│   ├── inlang/
│   │   ├── apps
│   │   ├── plugins
│   │   ├── lint-rules
│   │   ├── libraries
│   │   ├── documentation
│   │   └── README.md
│   ├── website/
│   │   └── README.md
│   ├── tsconfig.json
│   ├── package.json
│   └── package-lock.json
├── careers
├── documents
└── ...

```

**Comment by ivanhofer** [comment]
I would do it the other way around and don't put code into a `source-code` folder. Instead put `non-code` into a "not-source-code" folder.  Feel free to suggest a name for it ;)

Another question: since inlang and lisa are two different things (companies) should we split those into two git repositories?
Website could also be it's own repository but would also fit into the current inlang repository.

**Comment by samuelstroschein** [comment]
> since inlang and lisa are two different things (companies) should we split those into two git repositories?

I would leave everything in a monorepo to leverage [monorepo benefits](https://monorepo.tools/#why-a-monorepo). 

For marketing, different repos likely make sense, but we would lose monorepo benefits such easy dependency sharing (inlang builds on lisa) and cross-project tests (npm run test captures both lisa and inlang tests). Maybe we can create a placeholder lisa repository just for marketing purposes. Same for inlang, actually. This repo would become `x` and `x/inlang` is the mirrored repo from `x/monorepo/inlang`. 

Ugh, we should rename the organization to: 

a) reflect and communicate that we are building multiple products.
b) have dedicated marketing pages for each product 

```
labfrogs/monorepo

labfrogs/inlang     (mirrored from labfrogs/monorepo/inlang)
labfrogs/lisa       (mirrored from labfrogs/monorepo/lisa)
labfrogs/lisahub    (mirrored from labfrogs/monorepo/lisahub)
labfrogs/atelier    (mirrored from labfrogs/monorepo/atelier)
...
```

The structure above also entails that structure 1 or 2 are the way to go.

**Comment by samuelstroschein** [comment]
Folder structure 3 makes most sense in anticipation of "a lix repository can have apps [like inlang]" where the apps store application data in `repo/applications/*`. 

- keeping source-code divides source-code stuff from apps, and whatever. 
- moving monoreop package.json and everything into source-code is entailed

```diff
.
+|---- applications/inlang
├── source-code/
│   ├── lisa/
│   │   ├── client
│   │   ├── server
│   │   ├── filesystem
│   │   ├── documentation
│   │   └── README.md
│   ├── inlang/
│   │   ├── apps
│   │   ├── plugins
│   │   ├── lint-rules
│   │   ├── libraries
│   │   ├── documentation
│   │   └── README.md
│   ├── website/
│   │   └── README.md
│   ├── tsconfig.json
│   ├── package.json
│   └── package-lock.json
├── careers
├── documents
└── ...
```

**Comment by felixhaeberle** [comment]
@samuelstroschein can this be closed?
