### ISSUE TITLE
Clear separation between client and server code

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#313]
Maybe one / two export files per service → server.ts + client.ts

 same structure for every service

**Comment by samuelstroschein** [comment]
@leolurch I like your proposal of `server.ts` and client.ts export schemes instead of `index.ts` files. Were you only referring to services that need clear client/server differentiation?

**Comment by leolurch** [comment]
Yes, my main goal by going this way would be to prevent accidental imports of server modules in the client code. Don't know if this is real security risk for an open source problem though. Environment variables can't be leaked that way either, because of vite. 

Guess in the end it would just make the separation more explicit and you might find the code to work on faster.
