### ISSUE TITLE
language detection

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#466]
See https://github.com/inlang/inlang/blob/sdk-js-structure/rfcs/sdk-js/RFC.md#language-detection for reference.

The goal is to build reusable detector functions that can then be used by any adapter to detect the correct language. Similar to this approach: https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/detectors

A language negotioation algorithm is needed that takes an array of supported languages, the reference language and an array of detection strategies and outputs the best matching language.

Those reusable function will probably be wrapped by an adapter that passes the correct input to the function.

e.g.
```ts
import { detectLanguageFromAcceptLanguageHeader } from '@inlang/sdk-js'
const initSvelteKitAcceptLanguageDetector = (event: Event) =>
   () => detectLanguageFromAcceptLanguageHeader(event.headers.get('Accept-Language'))
```

**Comment by benjaminpreiss** [comment]
@ivanhofer What Do you mean with "reference language" in the above description?

**Comment by ivanhofer** [comment]
reference language is the inlang term for the default language or source language. e.g. for a german company it will be `'de'`, and `languages` are all languages where translations exist.

**Comment by benjaminpreiss** [comment]
> reference language is the inlang term for the default language or source language. e.g. for a german company it will be `'de'`, and `languages` are all languages where translations exist.

So it is the same as the parameter you termed "fallback locale" [here](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/detectors#detectors)?

**Comment by ivanhofer** [comment]
yes

**Comment by benjaminpreiss** [comment]
I am thinking of using the [official unicode list](https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/availableLocales.json) of available locales to have strict types regarding locales that can be entered as params. What do you think? That would introduce a synchronization overhead though to keep the list in sync with the unicode repo...

**Comment by ivanhofer** [comment]
We should not enforce users to use a certain standard. Users can work with any language code they want.

**Comment by benjaminpreiss** [comment]
Writing the navigator detector currently - How do you propose to handle the situation when window is not defined?

**Comment by ivanhofer** [comment]
The function will only be called if it runs on the client. Or at least the caller should make shure that this happens

**Comment by benjaminpreiss** [comment]
I was just thinking about the negotiation algorithm that the `detectLanguage` function should utilize...

#### Strategy ordering

I realized that there are detection scenarios:

- Detecting the user's preferred language (e.g. navigator.language)
- Detecting the requested language (e.g. root slug)

We introduce a flag `mode: "preference" | "request"`, which determines whether the user's preference or the request is prioritized in the detection. That is, in case a user wants to visit a very specific slug that is different from the user's preferred language, we can adjust the mode to accommodate that.

I would propose that we default to prioritizing preference over request. That means the strategies should have the following default precedence in the language detection algorithm:

1. `navigator`
2. `accept-language-header`
3. (fallback): `root-slug`

If the mode `"request"` is active, the order should be:

1. `root-slug`

#### Algorithm

Depending on the mode we are operating in, we only run the detectors that belong to that mode. The other detectors will only be run in case our preferred detectors return no results related to our available languages.

Let's say the strategy detectors return the following languages (sorted by probability, of course):

```
// 1st strategy detector returns ["en", "en-US", "de", "de-AT", "de-CH"]
// 2nd strategy detector returns ["fr-BE", "en-GB", "en"]
```

##### 1 - Sort by count, specificity and order of appearance

We will then count each language's occurrences with the following counting rules:

- A language without region gets added +1 for each entry with the same language (no matter if or what region it has) → "en" gets added +1 for e.g "en", "en-US", "en-GB" entries
- A language with region gets added +1 for each entry with the same language and region or the same language → "en-US" gets added +1 for both "en-US" and "en" entries, but not for "en-GB"

We also add another number to each language, that represents the average (weighted?) position for all used detectors. This average position calculates with the following formula:

`f(lang) = pos1( lang ) * n + pos2( lang ) * (n-1) + pos3 ( lang ) * (n-2) + ... + posn( lang ) * 1` where `n = total number of detectors USED` and `pos<number>( lang ) = array index in detector with number <number> OR total number of languages + 1 if not returned from detector`
This counting would then result in the following JS Map (only unique keys):

```
"en" -> {count: 4, avg_pos: 1*2+3=5}
"en-GB" -> {count: 3, avg_pos: 8*2+2=18}
"en-US" -> {count: 3, avg_pos: 2*2+8=12}
"de" -> {count: 3, avg_pos: 3*2+8=14}
"de-CH" -> {count: 2, avg_pos: 5*2+8=18}
"de-AT" -> {count: 2, avg_pos: 4*2+8=16}
"fr-BE" -> {count: 1, avg_pos: 8*2+1=17}
```

We can now sort this list with the following mechanisms:
1. by `count`
2. (if count is equal) by `avg_pos`

That results in the following sorted list:

```
"en" -> {count: 4, avg_pos: 1*2+3=5}
"en-US" -> {count: 3, avg_pos: 2*2+8=12}
"de" -> {count: 3, avg_pos: 3*2+8=14}
"en-GB" -> {count: 3, avg_pos: 8*2+2=18}
"de-AT" -> {count: 2, avg_pos: 4*2+8=16}
"de-CH" -> {count: 2, avg_pos: 5*2+8=18}
"fr-BE" -> {count: 1, avg_pos: 8*2+1=17}
```

##### 2 - Retrieve the first value that intersects with available languages

We can now get the first value that is also in our available languages list. If there is no exact match, we can return related values `"fr"` for a detected `"fr-BE"` or `"fr-BE"` for a detected `"fr"`. If there is not even a related match, we run the algorithm again, but this time with the fallback detectors.
 
Scenario 1: `availableLanguages = ["en-US", "de", "fr"]` -> `"en-US"`
Scenario 2: `availableLanguages = ["fr"]` -> `"fr"` (instead of `"fr-BE"`)
Scenario 3: `availableLanguages = ["es"]` -> RECURSION. We run the algorithm again, this time with the fallback detectors. Otherwise, we go to the next stage

##### 3 - No fallback detectors and/or no matching languages

We return the default language that was passed to `detectLanguage`

@ivanhofer What are your thoughts on this?

**Comment by ivanhofer** [comment]
I would not introduce the proposed `mode` flag.

The strategies are an array and developers can change the order by themself if they want to prioritize e.g. `cookies` over `accept-language-header` or the other way around.

And I would also not introduce the weighted algorithm. If `cookies` and founds a matching language that that match should be chosen.
If an application is configured like this: `['cookie', 'accept-language-header', 'ip-address']`, then a user would see the 'fr' version if the three algorithms resolve to `['fr', ['de', 'en'], 'fr']`. But as soon as that user crosses the border to germany then he would suddenly see the page in german, because the algorithms resolve to `['fr', ['de', 'en'], 'de']`.

Ideally the algorithms get set up like this:
 - the first entry is a static one e.g. a cookie
 - all other entries are "auto detection strategies"

So when the user first visits the website, the static one is not here and one of the auto-detection strategies kick in. Once a language get's found. the a cookie gets set and that language get used until the user manually switches language.

By choosing the first match, someone can also manually create a matching strategy with weighted algorithms.

**Comment by benjaminpreiss** [comment]
Okey, thanks for the feedback - I have now implemented the detect language functionality (with 2 tests still missing)

While I finish the last two steps, you can already have a look at it: https://github.com/inlang/inlang/tree/466-language-detection/source-code/sdk-js/src/detectors

**Comment by ivanhofer** [comment]
@benjaminpreiss I have created a draft PR and made some commets: https://github.com/inlang/inlang/pull/500
