### ISSUE TITLE
font takes forever to load

### ISSUE THREAD

**Issue by ivanhofer** [inlang/inlang#490]
## Problem

From my network request I can see that the font takes about 17 seconds to load.

## Steps to reproduce

1. Open the editor e.g. https://inlang.com/editor/github.com/rar9/SimpleCMS
2. Wait ...
3. Wait ...
4. Wait ...
5. Wait ...
6. Wait ...
7. the font get replaced with the real one (the content jumps around slightly)

### Expected behavior

The font should load quicker.

### Additional information (screenshots?)

![image](https://user-images.githubusercontent.com/21335119/229190855-0e02a71f-5fe7-4f03-95f3-c57984497f0e.png)

**Comment by ivanhofer** [comment]
@NiklasBuchfink @NilsJacobsen

**Comment by felixhaeberle** [comment]
True, this also happened to me and is really odd because there are techniques out there to easily prevent it. Let's figure it out on how we can do better here. 

I always refer to this article, now it's a bit outdated because 2 years old but should be helpful. Addy Osmani is also a great ressource for speeding up techniques. 

https://csswizardry.com/2020/05/the-fastest-google-fonts/

**Comment by NiklasBuchfink** [comment]
![Screenshot_20230406-161827__01__01.jpg](https://user-images.githubusercontent.com/59048346/230405850-0813401b-17d1-4e36-8e68-574770f2c780.jpg)

This could be the source of this issue 🤔
