### ISSUE TITLE
Modifications Required to Isomorphic-git

### ISSUE THREAD

**Issue by araknast** [inlang/inlang#558]
## Issue
Since we've decided to use isomorphic-git to implement our git-sdk we should make a decision on how to integrate it into the codebase. Currently we are importing it as a package, but as we are likely to make significant changes to the code it makes sense to include it's code as part of the git sdk.

In order to do this we will need to refactor the codebase to meet our needs. The minimal requirement for this is to migrate the isomorphic-git test suites from Jest to Vitest, and ensure the project builds with turbo.

Next would be to remove the dependency on polyfills, mainly `Buffer` and `http`.

## Proposal
I propose that we continuously integrate upstream changes from isomorphic-git into git-sdk in the following way:
1. Create a fork of isomorphic-git maintaining their build system
2. Automatically pull code from the fork and refactor it to work with the inlang build system
    - Vitest tests are generated automatically from the upstream Jest tests
    - Codebase is automatically refactored to build with turborepo
3. Any modifications to the isomorphic-git portion of the git sdk should be done in the isomorphic-git fork, from there they will be integrated into the git sdk automatically
4. Any upstream changes to isomorphic-git can be done by pulling from the fork

I know this is quite convoluted, but I figure the goals of git-sdk and isomorphic-git may begin to diverge significantly, and I feel this is the best way to fork in a way that still easily allows us to contribute upstream.

## Addendum: TypeScript
The inlang codebase is written in TypeScript, while the isomorphic-git codebase is written in JavaScript with jsdoc and `.d.ts` type declarations. The question arises of whether we should refactor to use inline type declarations in order to match with the rest of the codebase. I propose not, as it would be difficult to automate and I don't see much benefit to do so, but I'm curious to hear your thoughts.

**Comment by samuelstroschein** [comment]
> Currently we are importing it as a package, but as we are likely to make significant changes to the code it makes sense to include it's code as part of the git SDK.

I take this sentence as the goal of the refactoring (please comment if you disagree): 

Being able to use the git-sdk as part of the monorepo and thereby 

1. we can quickly adjust and iterate the "git-sdk" to our needs 
2. avoid publishing issues/the monorepo is always using the latest "git-sdk". 

Adjusting the "git-sdk" to our needs is important because the goals of the "git-sdk" differ from isomorphic git. Isomorphic git is a canonical git implementation in JS. We are building out a "version control based backend/database" for applications with _git compatibility_, not a _cononical git implementation. 

---

## Is upstream change sync worth it?

> I propose that we continuously integrate upstream changes from isomorphic-git into git-sdk in the following way [...]
> I know this is quite convoluted, but I figure the goals of git-sdk and isomorphic-git may begin to diverge significantly, and I feel this is the best way to fork in a way that still easily allows us to contribute upstream.

Given the diverging goals, and the desire to quickly iterate the git-sdk to our needs, I am wondering whether the effort of maintaining upstream changes is worth it. Trying to mirror upstream changes with an automatic system seems to be a very high effort. Manual copy & pasting absolutely necessary changes seem "more stable"/"worthier" the effort. 

1. The goals of isomorphic git and inlang's git-sdk differ. Do we expect upstream and our changes to be even "compatible"? For example, we are replacing the filesystem API due to the needs of the inlang editor. This change itself seems incompatible with isomorphic git. Using TypeScript would be incompatible as well. And migrating the codebase to native ESM resolution would require a bundler. In other words, a lot of overhead.  

2. Isomorphic git is unmaintained and outdated. Do we expect "high value" upstream changes? I don't think so. The majority of PRs are dependabot and README changes. Since we want to publish the git SDK, developers can use the maintained git-sdk we are developing anyways. 
 
## Requirements to make the git-sdk work in the monorepo

Minimum requirements: 

- [ ] migrate the codebase to ESM with moduleResolution `node16`. Inlang heavily relies on strict ESM resolution with dynamic imports. The rest of the codebase expects strict `node16` compatibility, see https://github.com/inlang/inlang/blob/main/tsconfig.base.json.

Good to have: 

- [ ] remove rollup in favor of `tsc` to simplify the build step
- [ ] remove node dependencies to avoid the requirement of polyfills (stuff like `Buffer`)
- [ ] replace http with fetch. 
- [ ] step-by-step migrate the codebase to TypeScript to avoid type errors, JSDoc confusion and overall align the git-sdk with the rest of inlang. 

> Codebase is automatically refactored to build with turborepo 

Turborepo simply executes npm scripts and caches them. There is no dedicated need to make the git-sdk work with turborepo. If the build step works (with tsc for example), turborepo will work automatically. The module https://github.com/inlang/inlang/tree/main/source-code/git-sdk already contains the required setup. 


---

@araknast It seems to me that upstream compatibility is not worth the effort, maybe even impossible, and the value to isomorphic git is low due to diverging goals. What are your thoughts?

**Comment by araknast** [comment]
> > Currently we are importing it as a package, but as we are likely to make significant changes to the code it makes sense to include it's code as part of the git SDK.
>
> I take this sentence as the goal of the refactoring (please comment if you disagree)
Yes, my original idea was to refactor the isomorphic-git codebase and integrate it into the git sdk, **but I think I've changed my mind on this now**. I made the proposal under the assumption that the isomorphic-git codebase would be trivial to integrate into ours, but based on my own attempts as well as the issues you outlined above regarding TypeScript and module resolution, I no longer think that's true. Considering the steps necessary and the effort required execute them, compared with the potential benefits, I think we're better off leaving isomorphic-git as an import and building on top of it. Ultimately, I think the time we would need to put into refactoring and maintaining an isomorphic-git fork could be better spent building in features we need for the sdk.

Regarding the concerns around differing goals, my initial git-sdk proposal was based around the idea of building the git-sdk on top of standard git functionality, that way we can easily switch out the implementation to something like libgit2 if need be. Any modifications we need in order to build the git-sdk (promisor remotes, partial clones, etc.) would be introducing features from canonical git into isomorphic-git, any divergence from the git api would be in git-sdk itself, a layer above isomorphic-git. Therefore, while or goals are different from those of isomorphic-git, our goals *for* isomorphic-git are the same i.e. a git implementation with the necessary features from the canonical version.

> Isomorphic git is unmaintained and outdated. Do we expect "high value" upstream changes? The majority of PRs are dependabot and README changes.
Isomorphic-git is outdated, though is technically maintained. The maintenece activity is not much, but it is work *we* would have to do for if we were to create hard fork. Having someone else do it is more time we get to spend on building things that matter. Upstream changes will probably not be significant, but the visibility of the repo alone makes it more likely for significant bugs/vulnerabilities to be discovered which is worth considering.

The approach I propose now is as follows:
1. Create a simple fork of isomorphic-git, separate from the rest of the inlang codebase, and using the isomorphic-git build tools. 
2. Implement the necessary parts of the git api (rebase, promisor remotes, etc.) in the fork
3. Build a package based on the fork and import it in git-sdk
4. Push changes from the fork upstream if desired

Ultimately my concern is and has always been efficient use of time. I figured integrating isomorphic-git into the codebase would allow us to develop upon it more easily. I was mistaken in thinking we could easily, automatically integrate the isomorphic-git codebase into our own, and I think the effort required to do so manually is not worth it. Making significant changes to isomorphic-git in order to modernize it and potentially optimize it for our uses would be nice, but I think now and for the time being we are better using it as is and focusing our efforts on more pressing matters.

**Comment by samuelstroschein** [comment]
> Ultimately, I think the time we would need to put into refactoring and maintaining an isomorphic-git fork could be better spent building in features we need for the sdk.

That makes sense and is what I planned with the initial version of the "git-sdk" (we should start calling it inlang-git): Re-export isomorphic git and build on top of it if required. 

But, I am wondering now whether that is the right approach. I anticipate a hard fork to happen sooner or later. Implementing real-time collaboration, sophisticated auth, a custom git server, and more doesn't seem to make sense with a layer (isomorphic-git) in between instead of directly using/modifying the files in the .git directory. Btw, with "Generally, diverging from a canonical git implementation [...]." I meant diverging from the git API/commands. We should (must?) have canonical git compatibility with the .git directory to be able to push and pull against and from repos. But everything that happens during "runtime" can likely diverge. 

If we believe that the main reason against a hard fork now is short-term higher refactoring work, the mid-and long-term benefits of faster iteration (no separate repos, no deployment pipeline required, end-to-end tests across the monorepo) and the fact that we have to do it anyways at some point could outweigh the short term burden. 

> Regarding the concerns about the isomorphic-git codebase, the codebase is fairly outdated, but it is technically maintained. The maintenance activity is not much, but it is work that we would have to do for if we were to create hard fork. Having someone else do it is more means we get time to spend on building things for ourselves.

Reducing our maintenance burden is the argument that puts me in favor of soft forking but we both do not expect much upstream activity. Hence, I don't know how much weight to give this argument. On the flip side, inlang-git is quite crucial to inlang. We can (and will) invest resources into maintenance. We even have a thesis that git/inlang-git could turn into a great backend for applications.  

> I was mistaken in thinking we could easily, automatically integrate the isomorphic-git codebase into our own, and I think the effort required to do so manually is not worth it.

I think the migration should be straightforward. Isomorphic git already seems to use strict Node16/ESM module resolution. Even if not, in most cases that's a question of adjusting import paths. Introducing TypeScript should also be doable because the JS files use JSDoc. We can set TypeScript to import from .js files. There will be no need to migrate the entire source code to TypeScript. We could do that step-by-step. Removing rollup and webpack seems trivial too as they only bundle (something we don't want btw) and don't polyfill/modify the code. 

The call yesterday felt quite productive. Shall we have a call for this discussion too? (I will go to bed now but would be available in 8 hours again)

**Comment by araknast** [comment]
> The call yesterday felt quite productive. Shall we have a call for this discussion too? (I will go to bed now but would be available in 8 hours again)

Sure, will ping you when I'm available
