### ISSUE TITLE
introduce plugin api

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#586]
See https://github.com/inlang/inlang/pull/570. 

- [x] #603
- [x] #604
- [x] #606
- [x] write documentation for plugin api  
- [x] refactor inlang/plugin-template to use new plugin api 
- [x] refactor inlang/standard-lint-rules to be a plugin (remove the concept of collection)
- [x] refactor samuelstroschein/inlang-plugin-json
- [x] refactor felixhaeberle/inlang-plugin-yaml https://github.com/felixhaeberle/inlang-plugin-yaml/pull/2
- [x] refactor ivanhofer/inlang-plugin-typesafe-i18n https://github.com/ivanhofer/inlang-plugin-typesafe-i18n/pull/2
- [x] implement plugin setup in editor, ide extension, cli 
- [x] update auto config generation to new config schema
- [x] update getting started documentation 

Nice to have: 

- [x] use zod to define config schema, see https://github.com/inlang/inlang/pull/605#discussion_r1181200520

**Comment by araknast** [comment]
The bug is [here](https://github.com/inlang/inlang/blob/9841e1be6b1fe3675ff0ebdf0a0ed5b3d5ee4d8e/source-code-git/fs/src/implementations/memoryFs.ts#LL85C1-L86C33) where an empty file evaluates to `undefined` due to the js `if` statement not being strict by default. Should be fixed by [this commit](https://github.com/inlang/inlang/pull/600/commits/cab9700b4a90f1abd2b5e3b2a6edd34f74b53163)
