### ISSUE TITLE
add @inlang/sdk-js / SDK to landing page

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#665]
## Problem

No mention of SDK on the landing page

## Solution

Create section for SDK on the landing page

**Comment by NiklasBuchfink** [comment]
It's not easy to communicate that we have a general SDK, more tightly integrated specific SDKs and that you can build your own solution. That's why we now have the "Integrates into any codebase" on the landing page with a highlight for the SvelteKit SDK. From there, the user should jump into the documentation.

These are redesigned to guide our users to the best fitting solution.

I would therefore close the issue for now. If you miss something, feel free to reopen it.
