### ISSUE TITLE
improve docs and `inlang` communication 

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#755]
Hey folks I opened this issue to track all the issues related to the docs. 
@NiklasBuchfink and I want to work on the communication initiative this week, so if there are any issues related to this topic feel free to put it in here and we will discuss it.

**Open issues:**
- [x] #700 
- [x] #698 
- [x] #670 

**Goal**
- The main call-to-action form marketing page / readme / ide-extension-store should point to the introduction page that's the place where people quickly need to understand inlang and get to their right starting point. A person that want's to install the Svelte SDK is probably not interested to do a manual setup. There shouldn't be loose ends in the docs. Everybody should be on track and pushed to a working setup.

**First steps**
✅ Propose User Flows get feedback on that
-> outcome:
- Three main userflows (not localized, no config, already have config)

Information Architecture Proposal -> [Loom Video](https://www.loom.com/share/d38891c6aea34395ab619294d2d1edf7)
<img width="1338" alt="image" src="https://github.com/inlang/inlang/assets/58360188/5ac3e123-5350-4ea9-a8ad-6c460a1cca86">

>this is work in progress and will be updated

**Comment by NilsJacobsen** [comment]
Hey folks, first draft of the docs flowcharts:
https://www.loom.com/share/e747389f455b4b2d97f71b9825630b99
Feedback appreciated

**Comment by samuelstroschein** [comment]
_Remarks on the [loom video](https://github.com/inlang/inlang/issues/755#issuecomment-1549287725)_

### 1. A solution like https://stonly.com/ might help us to create flows with less effort

Stonly is a no-code customer onboarding flow builder that we could embed in the docs. 

I used Stonly in my previous company. It makes onboarding flow building easy to the extend that I wouldn't know how to replicate such behavior with markdown. 

**Pros**

- less effort because no-code/visual flow builder
- built-in analytics to improve the flows

**Cons**

- contributors can't improve the flows (because they need access to stonly etc.)
- (expensive but that's a problem for the future)

Looking at stonly, I am thinking that we will rock the inlang editor! If someone defines an open standard file format for onboarding flows, similar to https://mermaid.js.org/, the inlang editor could have a view to edit such file format and (because it's a file!) we can simply embed it in the docs + contributors can just contribute!

_Off topic:_

@felixhaeberle remember when I said earlier that the `inlang.config.js` and markdown might be their own views? I think I nailed the mental distinction now: 

`View` = a "view" a file like markdown, inlang.config.js, mermaid, sqlite, JavaScript, etc. 
`Plugin` = extends a view (maybe the core of the inlang editor is a view by itself. Aka the editor is composed of "nested views") 

### 2. What is the common denominator for all flows? 

I am wondering if a distinction in so many flows and steps is required. 

The distinction (to me) seems to be "does a plugin for my use case exist or not?". If a plugin exists, the plugin (ideally) defines everything. No dedicated flows for sdk-js, ide extension, etc are required. If not, I have to write the config myself. The flow breaks down to:

1. A plugin exist 
2. A plugin doesn't exist


## Proposal

If the flow can be broken down by "a plugin configures the config for you", the setup experience should become easier and maintenance of the documentation much better. A good way could be to have a very simple flow of searching for plugins and show a fallback if no plugin exists. 

The entire flow can be found here https://link.excalidraw.com/l/1RmnkzJA3Ph/9kDJ32a0uSS.

### Step 1: Users opens the docs

The getting started greets the user with a search bar to search for plugins. That's it. Nice side benefit: We can track what plugins users are searching for, helping us prioritize plugins.


<img width="606" alt="CleanShot 2023-05-16 at 19 51 21@2x" src="https://github.com/inlang/inlang/assets/35429197/46a56d04-41e9-4349-b8eb-32115500a811">

### Step 2: A plugin exists

The user can click on a plugin of interest and gets to see a "plugin manifest". The plugin manifest describes the plugin, showcases an example config, what apps are supported, and more (in the future). 

Showcasing what a plugin supports seems to be a breakthrough in handling the different apps and better communicating how to set up each app. 

<img width="761" alt="CleanShot 2023-05-16 at 19 53 35@2x" src="https://github.com/inlang/inlang/assets/35429197/4f782cf5-63d0-454d-a4be-35b83d6627a7">

### Step 3: If no plugin exists, show how to manually configure the config

<img width="536" alt="CleanShot 2023-05-16 at 19 55 58@2x" src="https://github.com/inlang/inlang/assets/35429197/132ca27f-76cd-4346-babb-1ee177ef6259">

**Pros**

- less complex setup (find a plugin, done) 
- much less complex documentation (maintaining all different flows will be a massive burden)
- communicating what app works with which plugin

**Con**

- might be too simple (?)

**Comment by felixhaeberle** [comment]
@samuelstroschein I like the concept you outlined above but are against using a service. We have no idea where the docs are involving and this is our holy grail and shouldn't be locked into a service from a technical perspective.

Exclaimer: I haven't used the solution you are proposing before: it's simply that I like searching through the repository and find/change stuff that way. Really convenient source of truth.

**Comment by samuelstroschein** [comment]
@felixhaeberle Noted. I proposed it because the flows in the loom seemed very complex. My alternative proposal seems to have quite simple flows: 

```
already localizing -> search for a plugin -> copy a plugin config

not localizing -> select tech stack -> get forwarded to dedicated guide
```

**Comment by ivanhofer** [comment]
What about a getting stated guide/flow in the CLI?  `inlang init`

You get asked a few questions and then it spits out the correct `inlang.config.js`. This could be improved in the future to read `package.json` and to auto detect some things.

Another `inlang add` command could be used to add and configure certain plugins in a similar way.

A bit more effort, but the DX is far better than copying parts manually.

**Comment by felixhaeberle** [comment]
@samuelstroschein the inlang CLI has a huge potential in this field and is also what developers would expect from a "good infrastructure solution" to provide a CLI with getting started / setup command. This was eventually planned as inlang config init but we could rename it to just inlang init and thereby setting the file up and possible other tasks in the future. @ivanhofer Good idea!

**Comment by NilsJacobsen** [comment]
Thanks for the feedback:) 

**Maybe a first disclaimer:** 
The flows that I showed in the [loom](https://www.loom.com/share/e747389f455b4b2d97f71b9825630b99) are not flows that convert into pages per flow point. It is not an information architecture. That means that, this kind of flow can also result in your proposal for example or in 3 simple pages. The aim was to understand who is coming to the docs and what do they want. No screen related solution. Sorry folks if i undercommunicated that.

Appart from that I reviewed your proposals and take them as additional feedback to get to the information architecture that comes next and yes, that is screen related :D

**Here are some reactions:**
> A solution like https://stonly.com/ might help us to create flows with less effort @samuelstroschein 

Actually I have a same thoughts like @felixhaeberle about that. I also think that the value of the third party is not yet amortizing the efforts of setup and maintenance. My opinion is we should ship min. Monday a solution that is 200% better. It does not go all the way up to 500% because we do not have the time for that. So I would stick to the structure and change the page according to the real people that come to us and don't let them run in dead ends. That should be the holy grail for this week. 

> What is the common denominator for all flows? @samuelstroschein 

I agree we could simplify it a bit more. So in that feedback point u are basically questioning the manual and auto config flow. And I agree I like the config there or not better then my proposal. But I don't think that this is replacing the SDK docs. As we engineered it there is just a different setup than going green field to the docs. So I would say the denominator needs to be:

- Not localized
- No config
- Plugins for setup config

And now I am challenging it even further. Let's say you want to use the ide extension and you install it and get to the docs. Do you feel represented by these steps. In theory they need to go in the no config path but it is hard for them to understand what the config is and why they should care about it. I mean they have their own readme for sure but are we gonna catch them when they get in the docs. 

And these kind of questions we need to ask for every kind of infrastructure app. 

Question: Is the only plugin that gets named in the no config option the read and write plugin? To me that would make sense. 

> Proposal @samuelstroschein 

I like your proposal something like a plugin store is great to show the variety and have them all in a certain place. I would love to see this in the `Plugins for setup config` option. Tbh I actually think that model will be too easy for us. As I said the `Plugins for setup config` option get perfectly reflected in that, but no config users and also sdk user will be dropping off for sure. That architecture reminds me a bit of performance and real estate optimized designs. In my head the education is an important part of it. If we do not educate them we loos a lot of the devs when they need to understand plugins the config and how all of the infrastructure works together. 

To conclude, I like the simplicity, but maybe it is actually too easy for our use cases. Always keep in mind, we create a new technical architecture, if that will be our unfair advantage, people need to know about it. 

**Next steps:**
Gonna work on the information architecture and will update the summary of that issue on top. 
Thanks for collaborating. <3

**Comment by NilsJacobsen** [comment]
Hey people here is an update for the information architecture.
[Loom Video](https://www.loom.com/share/d38891c6aea34395ab619294d2d1edf7)

Aim:
- Solution that can be implemented till Monday
- Incorporate all user flows (not localized, no config, have config)
- Educate with folder structure (Getstarted, Apps, Plugins, SDK, Guide, References)
- Communicate the technical structure because that is a point to proof.

<img width="1327" alt="image" src="https://github.com/inlang/inlang/assets/58360188/17c8d597-9a98-4fb1-9caf-838edc70daf3">

**Comment by samuelstroschein** [comment]
@NilsJacobsen important point from the discussion: 

- We should differentiate in the communication between `apps`, `plugins` and `SDKs`. 
- Clearly communicate that `apps` work independently of `SDKs`. 

The issues for the plugin double config and plugin registry will follow (I respond to remote first).
