### ISSUE TITLE
should we rename `inlang-git` to a brandable name?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#824]
## Problem

1. It seems to become clear that `inlang-git` is not going to be "git". 

Using git in its name implicitly signals "this is git". Signaling that inlang-git is or will be like git seems undesirable. First, we don't want to confuse people that "this is and works like git". Second, we want a memorable brandable name that is likely not directly related to git. And lastly, if #823 is agreed on, using git as a "legacy" server protocol becomes weird: 

_Taken from #823:_

The code is confusing because we call git and can't clone a github repo? Why do we have to use legacy? What is legacy?

> ```ts
> // resolves from spec 
> await git.clone("https://git.inlang.com/v1/inlang/inlang-new")
> 
> // resolves as proxy 
> await git.clone("https://git.inlang.com/legacy/https://github.com/inlang/inlang")
> ```

## Proposal

A better way seems to be to get rid of git (calling it Lisa as a placeholder and in memories of the Apple Lisa computer): 

```ts
// resolves from spec 
await lisa.clone("https://lisa.inlang.com/v1/inlang/inlang-new")

// resolves as git proxy 
await lisa.clone("https://lisa.inlang.com/git/https://github.com/inlang/inlang")
```

- brandable name
- less confusion because we don't implicitly communicate "this is 100% git (and github, etc.) compatible"
- clear distinction to inlang as in "we have multiple products" like "inlang messages", "inlang lisa", etc. to attract developers to use inlang-git to build apps. 

## Additional information

- We can change the name in the future, but it will be a pain :D Whatever name we come up with, we need to make sure it is trademarkable. 

- The term "inlang messages" sneaked into this issue. It has been on my mind for some time to rename what we built so far to "Inlang Messages". It is becoming clear that we need to communicate differences between Messages, Documents, and in the future even the editor if https://github.com/inlang/inlang/discussions/677 is worked on.

**Comment by NilsJacobsen** [comment]
I agree, I think that is it what I talked about when I mentioned that people could be confused if they only work with [branches](https://gist.github.com/araknast/d80f8b64b2777e42b49fd9e89e5a1b13?permalink_comment_id=4576536#gistcomment-4576536) in the future. 

What about something with `version`, or even `v` is pretty well recognized. I also like something that is build around `time`, like `timemachine`from Mac.

**Comment by NiklasBuchfink** [comment]
I support this proposal. It's better to communicate that we're building something new with a Git-like architecture, rather than saying it's Git and then making a long list of the differences.
I think we can still point out what works with the classic Git providers and what advantages we offer compared to them. There will be a lot of educational work, but that's the point where we win new customers.

Let's brand it 👍 

> I also like something that is build around `time`, like `timemachine`from Mac.
Or just use `zeit` the old Vercel name ^^

**Comment by araknast** [comment]
For the time being, I think we should use an internal code name while we decide on a permanent name. Perhaps we should hold of on deciding a permanent name until the scope and nature of the project is more concrete.

"Project Lisa" sounds appropriate.

**Comment by NilsJacobsen** [comment]
Haha love it

**Comment by samuelstroschein** [comment]
`@lisa` is not available on NPM :( If we refer `inlang-git` as project `lisa`, it would be cool to change the npm package names

**Comment by samuelstroschein** [comment]
> Perhaps @inlang/lisa, or @inlang/project-lisa? 

Using inlang would be unsuitable. We want to establish a) lisa as a separate thing from inlang (inlang just happens to build on it, making communication of inlang easier as well) and b) `@lisa/fs` etc. wouldn't be possible. 

I reached out to the owner of the namespace lisa and asked if he is willing to give it to us.

**Comment by araknast** [comment]
> Using inlang would be unsuitable. We want to establish a) lisa as a separate thing from inlang (inlang just happens to build on it, making communication of inlang easier as well) and b) @lisa/fs etc. wouldn't be possible.

Is `@project-lisa` taken? I think that would be good in communicating that:
1. it is a metaproject encompassing multiple pieces of software 
2. it is under development and is not finished or even concretely defined yet
3. it has a development name that is subject to change

**Comment by samuelstroschein** [comment]
I like `@project-lisa`! 

> Is @project-lisa taken? 

Now it is, by us :P

<img width="370" alt="CleanShot 2023-05-24 at 19 44 50@2x" src="https://github.com/inlang/inlang/assets/35429197/5a1e48c6-7d44-4acd-9985-23f143292965">

Let's discuss names during the onsight in Amsterdam. This has no immediate priority

**Comment by NiklasBuchfink** [comment]
I talked a bit with ChatGPT and the IT department suggested Liza, which should be available as an npm and io domain. And there is a trashy liza.com site.

 Other suggestions:
- **Vix**: A short and simple name that suggests speed and flexibility. It is available as an npm shorthand and a domain name (vix.io).
- **Rev**: A name that sounds like “rev”, which is short for revision. It also implies river, which can symbolize the flow of data. It is available as an npm shorthand and a domain name (riv.io).

- **Zed**: A name that is easy to pronounce and spell. It also evokes the last letter of the alphabet, which can suggest completeness or finality. It is available as an npm shorthand and a domain name (zed.io).

- **Hex**: A name that suggests hexadecimal, which is a common format for representing data. It also sounds like “hacks”, which can imply creativity or innovation. It is available as an npm shorthand and a domain name (hex.io).

- **Lix**: A name that rhymes with “fix”, which can imply solving problems or improving performance. It also sounds like “links”, which can suggest connections or relationships. It is available as an npm shorthand and a domain name (lix.io).

- **Nix**: A name that sounds like “nix”, which means to cancel or reject something. It can also suggest Unix, which is a family of operating systems that are widely used for software development. It is available as an npm shorthand and a domain name (nix.io)

Nix is a bit funny because it means "Nothing" in German.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink ChatGPT is lying. nix.io is not available and neither on NPM.

Anyhow let's discuss names during the onsight in Amsterdam. This has no immediate priority

**Comment by felixhaeberle** [comment]
+1 project lisa

**Comment by samuelstroschein** [comment]
project lisa it is
