### ISSUE TITLE
don't require to commit every little change

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#835]
## Problem 

The editor requires every change in a message to be committed. This workflow slows down users, is annoying, and not even how git workflows "work".

@araknast remarked this problem in [using git more effectively in the editor](https://gist.github.com/araknast/d80f8b64b2777e42b49fd9e89e5a1b13#using-git-more-effectively-in-the-editor). 

<img width="686" alt="CleanShot 2023-05-23 at 10 08 02@2x" src="https://github.com/inlang/inlang/assets/35429197/e1d63af3-2b8c-4a49-99dd-ae2c8c4b8c25">

## Shannon's proposal

> "Everything is a [branch], and we have a lot of tools to work with [branches]."

In [using git more effectively in the editor](https://gist.github.com/araknast/d80f8b64b2777e42b49fd9e89e5a1b13#using-git-more-effectively-in-the-editor), @araknast  proposes to introduce a concept to inlang-git of everything being a branch to mitigate performance and the UX issue of being required to commit everything. 

**Pros**

- fewer concepts that seem to make git easier to use

**Cons**

- Mitigates but doesn't solve the root cause of the stated UX performance and "reason why everything is a commit" issues
- Higher risk of building the wrong thing because the proposed concept of everything is a branch doesn't stem from a requirement 
- The concept of everything being a branch needs to be explained. We'll get there eventually. But, I think it is too early to make drastic changes to git. 

## Samuel's counter-proposal 

Don't introduce a new concept. Leave git as is for now to avoid building the wrong thing. 

The UX issue of being required to commit everything can be solved by 1) changing the commit button to a save button and 2) have a dedicated commit button. A dedicated commit button resembles other git-based apps.

**Pros**

- Commits can have batched changes (solving the UX issue to 90%)
- Git concepts remain as is, for now, avoiding us to build the wrong thing
- Being forced to solve the root causes of issues. (change detection = we need semantic diffing; status matrix performance issues = we need a filesystem that communicates with inlang-git)

**Cons**

- Change detection doesn't work anymore. 

The reason why everything has been a commit was to show "you changed X messages" by using `statusMatrix`. This concept is gone. We can't use git anymore to detect Message related changes. Changes would by detected on a file/line level, not a Message level. To re-initiate message-based "change detection", we would need semantic diffing. Great news: Semantic diffing seems like a no-brainer quality-of-life feature for software engineering too. Fewer merge conflicts, and more fine-grained changes. 

- The status matrix performance issues wouldn't be solved. 

But, this is not an app problem. Inlang-git should be performened. Statusmatrix has the problem of iterating through the entire repo. If a filesystem exists that communicates with inlang-git what files changed, statusmatrix auto-filter based on the current file. This is the real solution to the performance issues. Trying to solve performance issues in the app mitigates a problem but doesn't solve the root cause.  

![CleanShot 2023-05-23 at 10 14 17@2x](https://github.com/inlang/inlang/assets/35429197/f04b2e27-5357-4911-8fd5-090adc4fef58)

**Comment by samuelstroschein** [comment]
@NiklasBuchfink @NilsJacobsen thoughts if this makes sense? We would loose the "local changes" feature though

**Comment by NiklasBuchfink** [comment]
1. "Commit" would then be a "commit & push", correct? I don't see the need to keep the changes inside the client application instead of pushing them directly to the remote repo.

2. which concept sounds better for "saving"?
a) "Autosave" and the whole thing behaves like a local form that is committed at the end. The downside to this is that it's harder to undo changes made accidentally. Our tiptap fields also provide a history, but it is not possible to push changes partially. We always commit the entire local form.
b) Still click "Save" per line and have an unsaved state for changes not included in commits. Clicking "Save" every time would still be annoying, even without the long load times.

3. is it still possible to check if there are local changes? If so, it is still possible to make the gitfloat jump in that case and show a state in it. This is also important to avoid leaving the windows with unconfirmed changes, as suggested in #714

**Comment by araknast** [comment]
> 1. "Commit" would then be a "commit & push", correct? I don't see the need to keep the changes inside the client application instead of pushing them directly to the remote repo.

Yes.

>     2. which concept sounds better for "saving"?
>        a) "Autosave" and the whole thing behaves like a local form that is committed at the end. The downside to this is that it's harder to undo changes made accidentally. Our tiptap fields also provide a history, but it is not possible to push changes partially. We always commit the entire local form.
>        b) Still click "Save" per line and have an unsaved state for changes not included in commits. Clicking "Save" every time would still be annoying, even without the long load times.

I prefer the "Autosave" concept, otherwise we still have the issue that the user needs to click n many buttons for each string they change. At the scale of a large project, I would imagine this becomes quite tedious.

>     3. is it still possible to check if there are local changes? If so, it is still possible to make the gitfloat jump in that case and show a state in it. This is also important to avoid leaving the windows with unconfirmed changes, as suggested in [Prevent the editor from being left with unpushed changes #714](https://github.com/inlang/inlang/issues/714)

At the moment the only way to determine if there are ustaged local changes is to call `statusMatrix`. If we could implement this in a way that this is only called once, i.e. when a user clicks to navigate away it might be doable. Otherwise we would need to either a) improve the performance of `statusMatrix` or b) integrate git into the filesystem. I like option b, but of course we would need to plan out how we do this.

**Comment by samuelstroschein** [comment]
>> @NiklasBuchfink  3. is it still possible to check if there are local changes? If so, it is still possible to make the gitfloat jump in that case and show a state in it. This is also important to avoid leaving the windows with unconfirmed changes, as suggested in https://github.com/inlang/inlang/issues/714

> @araknast  At the moment the only way to determine if there are ustaged local changes is to call statusMatrix. If we could implement this in a way that this is only called once, i.e. when a user clicks to navigate away it might be doable. Otherwise we would need to either a) improve the performance of statusMatrix or b) integrate git into the filesystem. I like option b, but of course we would need to plan out how we do this.

A dirty trick could be a change counter in the editor on a Message level. That entails the need to keep Save though which I think is fine because we have a `CMD + S` shortcut. 

Even if we improve the performance of `statusMatrix`, we can't detect changes on a Message level. Only on a resource level.

**Comment by samuelstroschein** [comment]
The `statusMatrix` performance issues might be caused by https://github.com/inlang/inlang/issues/839.
