### ISSUE TITLE
Solve root-causes in inlang-git, don't work around problems in apps?

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#836]
## Proposal

Have a design guideline for inlang-git that states 

> "Solve root causes in inlang-git, don't work around problems in apps". 

Inlang-git is supposed to become a backend for apps. To become a good backend, inlang-git must work well for a variety of apps. Thus, problems that apps like the inlang editor face with inlang-git should be solved in inlang-git itself. We should not be building workarounds in the editor or other apps to mitigate issues we face with inlang-git. Ultimately, the issues will resurface in other apps, making inlang-git a "bad" backend. 

The design guideline has been prompted by @araknast proposal for "everything is a branch" which correctly identified multiple issues in the inlang editor. Namely, a UX flaw that triggers a performance flaw. Probably overseen by @araknast, the UX flaw is a direct result of a missing feature in inlang-git (semantic diffing). @araknast proposed a change that would mitigate the performance flaw in the editor by calling it less often. The wrong solution in my opinion, see https://github.com/inlang/inlang/issues/835. I propose to fix the performance issues of the underlying implementation instead. Fixing underlying implementation issues, without building workarounds in apps, has multiple upsides: 

- the problem is solved for not just one but many apps
- the DX of using inlang-git is increased by not being required to implement workarounds 
- the UX of inland-git-based apps is increased because apps don't need to change concepts to workaround inlang-git limitations.

**Comment by araknast** [comment]
> The design guideline has been prompted by @araknast proposal for "everything is a branch" which correctly identified multiple issues in the inlang editor. Namely, a UX flaw that triggers a performance flaw. Probably overseen by @araknast, the UX flaw is a direct result of a missing feature in inlang-git (semantic diffing). 

Hmm, if I'm understanding correctly, we need a way for the editor to know exactly which strings have been edited so that it can inform the user? Semantic diffing would allow us to confidently know which _lines_ changed, but wouldn't we still need to invoke `statusMatrix` to know which _files_ changed? 

>> "Solve root causes in inlang-git, don't work around problems in apps".

Agreed 100%, but the "root cause" of the issue here seems to be the performance of `statusMatrix`. Specifically it seems to run extremely slowly in the browser. This is not the case when using `statusMatrix` on the client, with either `node`, `memfs`, or `memoryFs`.

 The issue I fear, is that the root cause of the problem is either 1) inherent to our ecosystem (js, solidjs, and running in the browser), or b) buried inside it. In other words, this seems like it will be a very hard bug to fix. Ideally in the long run we would fix `statusMatrix`, but the proposed solution of auto-staging and then creating one large commit was intended as an immediate fix we could do without building any new functionality.

**Comment by samuelstroschein** [comment]
> To me a git integrated filesystem seems like a workaround to underlying performance issues in statusMatrix itself. Running statusMatrix on a large repository should be fairly instant, and indeed it is in node with memoryFs. Thus there is something about the browser/editor environment that is making it run much slower than normal. 

Wups. You are right! Ideally, the filesystem wouldn't need to specifically "communicate with inlang-git". I thought filesystem operations slow down statusMatrix which could be avoided with `filter`. But, if filesystem operations cause the slowness, the filesystem operations itself should be improved rather than a workaround of setting filter.
