### ISSUE TITLE
Move ide extension config back to core

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#856]
## Context

_Long discussion that the ide extension plugin shouldn't exist https://github.com/inlang/inlang/issues/758_

> The ide-extension-plugins doesn't set any config properties because it defines additional properties outside of @inlang/core. Thus, nobody understands this plugin as it shouldn't exist in the first place.

## Proposal

- [ ] move the ide extension config to core
- [ ] delete the ide extension plugin in source code
- [ ] delete ide extension plugin on NPM
- [ ] update docs
- [ ] ide extension support in json plugin ?

**Comment by felixhaeberle** [comment]
@samuelstroschein can you add a working example config to the README of the ide extension? Or does the json plugin has ide extension support? Because we are showing a config with the json plugin in the getting started section and I'm not sure if people are getting it right if they copy that snippet?

**Comment by samuelstroschein** [comment]
@felixhaeberle good remark. We should remove the config entirely and refer to the plugin registry #778 instead. 

There is not a single config that works for the ide extension and can be shown in the readme.
