### ISSUE TITLE
Update localization to globalization

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/inlang#894]
Update landing page to globalization infra.

Possible headline (Everything you need to scale your global app)

Work through the developer checklist and check storytelling.

Old:
![image](https://github.com/inlang/inlang/assets/58360188/bcd91dc2-8856-42b3-996e-6031f2e19b00)

**Comment by samuelstroschein** [comment]
How about "Infrastructure to go global" instead of "globalization infrastructure"? 

- globalization infrastructure doesn't describe the "effect" of _being able to go global_
- globalization has a negative connotation

**Comment by samuelstroschein** [comment]
I remember PotHog and Stripe suggesting describing the product rather than the marketing copy for developer audiences. 

Stripe: "Financial infrastructure for the internet"
PostHog: "The open source Product OS"
Inlang: "Globalization infrastructure for software"  

Looking at the taglines, "globalization infrastructure for software" seems to fit right in. "Infrastructure to go global for software companies" would be too long. 

Let's not overthink this too much. I vote for globalization infrastructure for software for now

**Comment by NilsJacobsen** [comment]
Actually this issue is not only about the tagline but also how we tell the story across the page. Introducing globalization needs to be reviewed over the page. Actually I like that too -> infrastructure to go global

**Comment by samuelstroschein** [comment]
@NilsJacobsen Can you prioritize this issue because of https://github.com/inlang/internal/issues/64? 

I like "infrastructure to go global".
