### ISSUE TITLE
How we deal with issues

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#928]
### Legend

🟢 Open issue - Will be completed in the foreseeable future. 
✖️ Not planned [in the next weeks] - Upvote/comment on the issue to increase priority. 
🟣 Closed issue - Has been completed. 

#### 1. We treat issues as tasks that have to be completed in the foreseeable future.

- Keeping an overview of what needs to be handled immediately. 

#### 2. Default assign the responsible team member to ensure that an issue is handled. 

- The assigned team member can assign a priority or mark the issue as not planned due to X. 

#### 3. Issues that have no immediate priority will be closed as "not planned [in the next weeks]".

- Closing non-immediate issues helps us clean up our "to-do list" and keep an overview of issues that need to be handled.

#### 4. Use the weekly milestones to communicate when an issue is going to be handled. 

- External users or team members know when something will be worked on without asking. 
- The milestone provides a good filter for "What do I need to get done this week?". 

---

_This issue is updated as our processes evolve._

**Comment by samuelstroschein** [comment]
@inlang/team Read the guidelines. If you disagree, discuss on this issue and what should be changed. 

- this issue is an evolving issue. The description will be updated as we adapt our processes. 
- pinned to the top of issues to communicate the guidelines to external users.
- closing this as not planned because this is not a task but exists to be pinned on top the issues

**Comment by NilsJacobsen** [comment]
I actually like the outlined process, I think @ivanhofer's mindset and this approach can not be living together. Eather we treat the issues as a todo list for max 4 weeks or as a big backlog

**Comment by samuelstroschein** [comment]
@ivanhofer I updated the description to clarify the intentions of the guidelines. 

I agree with @NilsJacobsen remark. Either an issue is important and needs to be fixed within the next weeks, or it is not. If it's not, it will just lay around and nobody will fix it anyways. I added: 

- the goal to avoid a backlog of issues
- if an issue is a long-term task as part of a project, add it to the project and re-open once it will be handled. 


---

> We will probably get a lot of duplicated issues because no open issue exists for something. 

Sounds like such an issue has a high priority then (like being a bug) and shouldn't be closed in the first place. 

> And once closed, we will probably forget them. 

That's the goal :D We have resource constraints and need to prioritize how our time is invested. If an issue is forgotten, it was probably not important. 

> I think adding a label "low prior"

Low priority issues will be treated as backlog aka never worked on. The result is likely an endless list of "dead" issues like we see on many other OSS repos.

**Comment by NiklasBuchfink** [comment]
I like the outlined process for dealing with issues 👍

**Comment by jannesblobel** [comment]
Since we also use the issues as a discussion round, we should add voting and force people to do a Loom. 

We can save much time with a loom instead of a long discussion with room for misunderstandings.
 

Voting Section after x time 
- write a conclusion/ result/ next steps
- min 50% of all affected members should vote with a 👍  ( in case of a tie, the 👎 wins)

**Comment by araknast** [comment]
Agreed on closing issues that are not a high priority, although I think we should still mark the closed issues as 'low priority' or something of the sort so we can easily go back and find them later when we have spare resources. Also agree on using loom/voting when we use GitHub issues to track discussions. Maybe the incorporation of voting/short videos into issues could be a feature for 'Lisa-Hub' :wink: .

**Comment by felixhaeberle** [comment]
@inlang/team 

I adjusted the section on how we inform the dedicated team about potential issues.

> #### 2. Default assign the responsible team to ensure that an issue is handled. 
>
> - The assigned team can assign a priority or mark the issue as not planned due to X. 
Responsible teams can be found here: https://github.com/orgs/inlang/teams

**Comment by samuelstroschein** [comment]
The latest "tag a team" process doesn't work.

- Teams can't be assigned to issues.
- The result are issues that have no assigned person which increases the likelihood that they won't be handled. 
- Tagging the entire team is noisy when the POC (person of contact) can be assigned. The POC forwards the issue if needed.

I started assigning the POC (again). Should I update the issue?

**Comment by felixhaeberle** [comment]
I think the group tagging works because the group and everybody gets a notification –> the group escalates it. 
It's simply ignoring the process if you don't assign, which is bad behavior.

Furthermore, it's relatively easy to spot not assigned issues in the /issues list view, so we likey don't miss one.

**Comment by samuelstroschein** [comment]
> I think the group tagging works because the group gets a notification –> the group escalates it. 

That's now what is happening. If a group is tagged, nobody is in charge because somebody needs to step forward to take charge. 

> Furthermore, it's relatively easy to spot not assigned issues in the /issues list view, so we likey don't miss one.

In other words, the process doesn't work that's why someone needs to invest time to assign people in charge. 
 
---

I propose to assign the POC that needs to handle the issue without anyone stepping forward.

**Comment by felixhaeberle** [comment]
I go with what the majority of people think is right.

**Comment by NilsJacobsen** [comment]
Maybe POC is in charge ?

**Comment by samuelstroschein** [comment]
> Maybe POC is in charge ? 

That's what I am proposing. 

## Problem

The latest "tag a team" process doesn't work.

- Teams can't be assigned to issues.
-  The result are issues that have no assigned person which increases the likelihood that they won't be handled.
- Tagging the entire team is noisy when the POC (person of contact) can be assigned. The POC forwards the issue if needed.

## Proposal 

Change the assignation of issues from "tag a team" to "assign the POC". 

- tagging a team leads to "nobody stepping forward" to handle an issue (opt-in)
- tagging the POC leads to "the POC of a team must handle or delegate the issue" (opt-out)

Please vote with 👍 or 👎 

--- 

_Hiding previous comments to de-noise the issue_

**Comment by jannesblobel** [comment]
Missing points in @samuelstroschein proposal: 

What was the idea of tagging the entire team? 
> The group escalates it.

So you should Tag a team if it is crucial, and the team should decide together. 
If you only assign the POC, all the team members will not know about it, and maybe someone may have valid concerns/thoughts about this issue. 

BTW: 
The team tagging works well for me. e.g., **I love it.** 

## Proposal: 
**I think the intermediate solution is tagging the team and assigning the POC.**

<br>
<br>


## Notes: 
> Hiding previous comments to de-noise the issue is not a good idea. 

Bad idea because I read your proposal and agreed. I only opened the comments afterward by chance and saw @felixhaeberle comments, which made me think again. 


> I go with what the majority of people think is right.

@felixhaeberle Please don't vote for solutions if you are unhappy with the proposal. I would always prefer abstention. That's the only way to see how many people were really convinced, and you obviously weren't 100%. 


> Tagging the entire team is noisy when 

@samuelstroschein I believe we all have to learn to ignore some issues for a moment and wait until the POC tags us again. Maybe we have to unsubscribe on some issues if we are not interested.

**Comment by samuelstroschein** [comment]
@jannesblobel the POC can tag the team if it's relevant or only the person of interest. 

Fact remains that opt-in (tagging) leads to unhandled issues vs opt-out (assigning the POC). Let's try assining the POC and see how it goes.

**Comment by NilsJacobsen** [comment]
I think tagging the team and the POC is the best solution. Because otherwise, a lot of information is not getting to the team. In our stage, that is often relevant. So why not? I would say if it is regarding the editor, the whole team should know about that issue, but the POC is responsible for that this is handled in the suitable timeframe.

**Comment by jannesblobel** [comment]
Tag only the POC

**Comment by jannesblobel** [comment]
Tag POC and the team

**Comment by samuelstroschein** [comment]
Assign POC and tag the team
