### ISSUE TITLE
Google description shows HTML for docs

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#995]
## Problem

<img width="500" alt="Bildschirmfoto 2023-06-26 um 11 47 23" src="https://github.com/inlang/inlang/assets/34959078/1445fa9b-13f2-472e-98db-2fd078dc4d05">

### Expected behavior

Should display the correct meta data description.

## Steps to reproduce

1. Go to 'google.com'
2. Google 'inlang documentation'
3. See the error

**Comment by felixhaeberle** [comment]
@inlang/website this is something you might be interested in.

**Comment by floriandwt** [comment]
@NilsJacobsen should I assign myself to this issue? Working on some docs-things anyways.

**Comment by NilsJacobsen** [comment]
Sure thanks man.

**Comment by floriandwt** [comment]
@felixhaeberle is inlang already connected to Google's Search Console? I think we have to manually crawl the page again, all sites are showing it correctly:
<img width="589" alt="Screenshot 2023-06-28 at 4 44 08 PM" src="https://github.com/inlang/inlang/assets/92092993/d8058ad7-ec4e-4384-a6aa-1607ffbe54f8">

@NilsJacobsen I've seen 3 weeks ago you implemented the new structure for the docs. Was Frontmatter or something similar already used before that? Because it could be that Google just has an old cache, but 3 weeks seems like a long time…

**Comment by floriandwt** [comment]
Addition: I've searched some other pages from the docs, and just found the Quickstart – nothing else. I'll improve SEO in the docs anyways, so when I'm done I recrawl inlangs website manually.

**Comment by felixhaeberle** [comment]
@floriandwt Thank you!! I think we are missing out on a proper SEO configuration, and this is also manifested by your link research in Google where only the Quickstart & Documentation links are found, but nothing else.

Quick feedback to the above sentence, I would say: "Learn how to get started with inlang, the globalization infrastructure."

**Comment by NilsJacobsen** [comment]
Sounds like a good plan:)
I barely tackled SEO yet so keep going🚀

**Comment by floriandwt** [comment]
@samuelstroschein if you have time you could add `google-site-verification=_3b_tImKniiiTc3qygcHKTFEg0VUCqQyy9u6rIscm6U` as a TXT-record to inlang's domain so we can crawl it manually if we adjust SEO related things.

**Comment by samuelstroschein** [comment]
I added you all to search console.

**Comment by floriandwt** [comment]
Tested it again in normal and private browsing. Seems to be resolved (searched 'inlang documentation').

<img width="624" alt="Screenshot 2023-06-30 at 11 51 06 AM" src="https://github.com/inlang/inlang/assets/92092993/258b04d4-872e-4d04-9b69-d560a538cfa3">
